from textwrap import dedent

from config import AUTHOR, CONTACT, MOD_NAME, MOD_VERSION, REPO_URL, SOURCE_DIRS, RESOURCE_TYPES, SKIN_KEYBINDS, VARIANT_KEYBIND

def create_header():
    text = f"{MOD_NAME} v{MOD_VERSION}"
    header = f"; {text} {'-' * (60 - len(text))}\n\n"

    return header


def create_toggle(type, keybind) -> tuple[str, str]:
    return (
        f"global persist $use{type} = 1\n",
        dedent(f"""\
        
            [KeyToggle{type}]
            key = {keybind}
            type = cycle
            $use{type} = 0,1  
        """)
    )

def create_constants():
    has_variants = len(SOURCE_DIRS) > 1
    has_types = len(RESOURCE_TYPES) > 1
    types = set(RESOURCE_TYPES) if has_types else set()

    if not has_variants and not has_types:
        return ""

    section = dedent(f"""\
        ; Constants {'-' * (60 - 9)}
        
        [Constants]
    """)

    # var creation for variant
    if has_variants:
        section += "global persist $variant = 0\n"

    # var creation of toggles
    select_toggle, tab_toggle, round_toggle, portrait_toggle = (("", ""),) * 4
    if has_types:
        if len(SKIN_KEYBINDS) < len(types):
            print(
                "Not enough keybinds in config! Make sure the SKIN_KEYBINDS "
                "list has enough entries to match the types listed in "
                "RESOURCE_TYPES!"
            )
            print("Cannot resolve error automatically, aborting...")
            exit(1)

        if "Select" in types:
            select_toggle = create_toggle("Select", SKIN_KEYBINDS[0])
            section += select_toggle[0]
        if "Tab" in types:
            tab_toggle = create_toggle("Tab", SKIN_KEYBINDS[1])
            section += tab_toggle[0]
        if "Round" in types:
            round_toggle = create_toggle("Round", SKIN_KEYBINDS[2])
            section += round_toggle[0]
        if "Portrait" in types:
            portrait_toggle = create_toggle("Portrait", SKIN_KEYBINDS[3])
            section += portrait_toggle[0]

    # keybind section for variants
    if has_variants:
        if not bool(VARIANT_KEYBIND) and len(SOURCE_DIRS) > 1:
            print(
                "VARIANT_KEYBIND is empty, but multiple variants are present! "
                "Please specify a variant keybind in `config.py`!"
            )
            print("Cannot resolve error automatically, aborting...")
            exit(1)

        section += dedent(f"""\
        
            [KeySwapVariant]
            key = {VARIANT_KEYBIND}
            type = cycle
            $variant = {','.join(str(i) for i in range(len(SOURCE_DIRS)))}
        """)

    # keybind sections for types
    section += select_toggle[1]
    section += tab_toggle[1]
    section += round_toggle[1]
    section += portrait_toggle[1]

    return section

# todo: the meat
def create_override():
    pass

def create_footer():
    has_author = bool(AUTHOR)
    author_line = f"; Generated by {AUTHOR}'s {MOD_NAME} generator :3c"

    has_contact = bool(CONTACT)
    contact_line = f"; If you have any issues with this mod, please contact me at {CONTACT}!"

    has_repo = bool(REPO_URL)
    repo_line = f"; The source code for this mod generator can be found at: {REPO_URL}"

    return dedent(f"""\
    
        {author_line if has_author else ""}
        {contact_line if has_contact else ""}
        {";" if has_repo else ""}
        {repo_line if has_repo else ""}
    """)
